import { Loader2Icon } from 'lucide-react'

import { cn } from '@/lib/utils'

/**
 * The one spinner in the console. Skeletons cover waits where we know the shape
 * of what is coming; this covers the ones where we do not -- a filter round
 * trip, a form in flight -- and where the control itself has to stay on screen.
 *
 * It lives here rather than in components/ui because that directory is
 * generated by the shadcn CLI and is not hand-edited.
 */
export function Spinner({
  className,
  label = 'Loading',
}: {
  className?: string
  label?: string
}) {
  return (
    <Loader2Icon
      role="status"
      aria-label={label}
      className={cn('size-4 shrink-0 animate-spin text-muted-foreground', className)}
    />
  )
}
